"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { AppShell } from "../components/AppShell";

const API = process.env.NEXT_PUBLIC_API_BASE ?? "/api/backend";

type CandidateStatus="pending"|"reviewing"|"on_hold"|"approved"|"rejected"|"selected"|"linked";
type BaseCandidate={name:string;marketplace:string;country:string;source_price:number;target_price:number;shipping_cost:number;platform_fee_rate:number;ad_cost_rate:number;competition_score:number;trend_score:number;brand_score:number;total_cost:number;gross_profit:number;margin_rate:number;total_score:number;recommendation:string;explanation:string};
type SavedCandidate=BaseCandidate&{id:number;status:CandidateStatus;notes:string;tags:string};
type ReviewDraft={status:CandidateStatus;notes:string;tags:string};
const statusLabels:Record<CandidateStatus,string>={pending:"대기",reviewing:"검토중",on_hold:"보류",approved:"승인",rejected:"거절",selected:"선정",linked:"프로젝트 연결"};
const statusOptions=Object.entries(statusLabels) as [CandidateStatus,string][];

export default function SourcingPage(){
 const [token,setToken]=useState(""); const [email,setEmail]=useState("admin@jarvis.example.com"); const [password,setPassword]=useState("change-me-now");
 const [keyword,setKeyword]=useState(""); const [marketplace,setMarketplace]=useState("coupang"); const [country,setCountry]=useState("KR");
 const [results,setResults]=useState<BaseCandidate[]>([]); const [saved,setSaved]=useState<SavedCandidate[]>([]); const [tab,setTab]=useState<"search"|"saved">("search");
 const [sort,setSort]=useState<"score"|"margin"|"recent">("score"); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(""); const [reviewDrafts,setReviewDrafts]=useState<Record<number,ReviewDraft>>({});
 useEffect(()=>{const t=localStorage.getItem("jarvis_token");if(t)setToken(t)},[]);
 useEffect(()=>{if(token)void loadSaved()},[token]);
 useEffect(()=>{setReviewDrafts(previous=>{const next={...previous};for(const item of saved){if(!next[item.id])next[item.id]={status:item.status,notes:item.notes??"",tags:item.tags??""}}return next})},[saved]);
 function clearSession(){localStorage.removeItem("jarvis_token");setToken("")}
 async function authFetch(path:string,init:RequestInit={}){const h=new Headers(init.headers);h.set("authorization",`Bearer ${token}`);if(init.body)h.set("content-type","application/json");const r=await fetch(`${API}${path}`,{...init,headers:h,cache:"no-store"});if(r.status===401)clearSession();return r}
 async function login(e:FormEvent){e.preventDefault();setBusy(true);const r=await fetch(`${API}/api/v1/auth/login`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email,password})});setBusy(false);if(!r.ok){setMessage("로그인 정보를 확인하세요.");return}const d=await r.json();localStorage.setItem("jarvis_token",d.access_token);setToken(d.access_token)}
 async function loadSaved(){const r=await authFetch("/api/v1/sourcing/candidates");if(r.ok)setSaved(await r.json())}
 async function search(e:FormEvent){e.preventDefault();setBusy(true);setMessage("");const r=await authFetch("/api/v1/sourcing/search",{method:"POST",body:JSON.stringify({keyword,marketplace,country})});setBusy(false);if(!r.ok){setMessage(`검색 실패: ${await r.text()}`);return}setResults(await r.json());setTab("search")}
 async function saveCandidate(c:BaseCandidate){setBusy(true);setMessage("");const r=await authFetch("/api/v1/sourcing/candidates",{method:"POST",body:JSON.stringify({name:c.name,marketplace:c.marketplace,country:c.country,source_price:c.source_price,target_price:c.target_price,shipping_cost:c.shipping_cost,platform_fee_rate:c.platform_fee_rate,ad_cost_rate:c.ad_cost_rate,competition_score:c.competition_score,trend_score:c.trend_score,brand_score:c.brand_score})});setBusy(false);if(r.status===409){setMessage("이미 저장된 상품 후보입니다.");return}if(!r.ok){setMessage(`저장 실패: ${await r.text()}`);return}setMessage(`${c.name} 저장 완료`);await loadSaved();setTab("saved")}
 async function saveReview(id:number){const draft=reviewDrafts[id];if(!draft)return;setBusy(true);setMessage("");const r=await authFetch(`/api/v1/sourcing/candidates/${id}/review`,{method:"PATCH",body:JSON.stringify(draft)});setBusy(false);if(!r.ok){setMessage(`검토 저장 실패: ${await r.text()}`);return}setMessage("후보 검토 정보를 저장했습니다.");await loadSaved()}
 function updateDraft(id:number,patch:Partial<ReviewDraft>){setReviewDrafts(previous=>({...previous,[id]:{status:previous[id]?.status??"pending",notes:previous[id]?.notes??"",tags:previous[id]?.tags??"",...patch}}))}
 const sorted=useMemo(()=>{const c=[...saved];if(sort==="score")return c.sort((a,b)=>b.total_score-a.total_score);if(sort==="margin")return c.sort((a,b)=>b.margin_rate-a.margin_rate);return c.sort((a,b)=>b.id-a.id)},[saved,sort]);
 if(!token)return <main className="login"><form onSubmit={login} className="card login-card"><h1>JARVIS</h1><p>통합 조종석 로그인</p><input value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" value={password} onChange={e=>setPassword(e.target.value)}/><button disabled={busy}>{busy?"확인 중...":"로그인"}</button><span>{message}</span></form></main>;
 return <AppShell active="sourcing" kicker="PRIMARY MODULE" title="AI Sourcing" description="검색, 저장, 검토 상태, 태그와 메모를 한 흐름으로 관리합니다." onLogout={clearSession}>
 <form className="card search-bar" onSubmit={search}><input required placeholder="예: 휴대용 선풍기" value={keyword} onChange={e=>setKeyword(e.target.value)}/><select value={marketplace} onChange={e=>setMarketplace(e.target.value)}><option value="coupang">쿠팡</option><option value="naver">네이버</option><option value="amazon">Amazon</option><option value="shopee">Shopee</option><option value="lazada">Lazada</option></select><input value={country} onChange={e=>setCountry(e.target.value)}/><button disabled={busy}>{busy?"처리 중...":"후보 검색"}</button></form>
 <div className="tab-row"><button className={tab==="search"?"tab active":"tab"} onClick={()=>setTab("search")}>검색 결과 ({results.length})</button><button className={tab==="saved"?"tab active":"tab"} onClick={()=>setTab("saved")}>저장 목록 ({saved.length})</button></div>{message&&<p className="notice">{message}</p>}
 {tab==="saved"&&<div className="saved-toolbar"><span>저장된 후보는 상태, 태그, 메모와 함께 유지됩니다.</span><select value={sort} onChange={e=>setSort(e.target.value as typeof sort)}><option value="score">점수 높은 순</option><option value="margin">마진 높은 순</option><option value="recent">최근 저장 순</option></select></div>}
 <section className="results-grid">{tab==="search"&&results.map(i=><article className="card result-card" key={`${i.name}-${i.marketplace}`}><div className="result-top"><div><small>{i.marketplace.toUpperCase()} · {i.country}</small><h3>{i.name}</h3></div><div className="score">{i.total_score}</div></div><div className="stats"><span>매입가 <b>{i.source_price.toLocaleString()}</b></span><span>판매가 <b>{i.target_price.toLocaleString()}</b></span><span>순이익 <b>{i.gross_profit.toLocaleString()}</b></span><span>마진 <b>{i.margin_rate}%</b></span></div><p>{i.explanation}</p><button className="approve" disabled={busy} onClick={()=>void saveCandidate(i)}>분석 목록에 저장</button></article>)}
 {tab==="saved"&&sorted.map(i=>{const draft=reviewDrafts[i.id]??{status:i.status,notes:i.notes??"",tags:i.tags??""};return <article className="card result-card" key={i.id}><div className="result-top"><div><small>{i.marketplace.toUpperCase()} · {i.country}</small><h3>{i.name}</h3></div><div className="score">{i.total_score}</div></div><div className="stats"><span>순이익 <b>{i.gross_profit.toLocaleString()}</b></span><span>마진 <b>{i.margin_rate}%</b></span><span>판정 <b>{i.recommendation}</b></span><span>상태 <b>{statusLabels[i.status]??i.status}</b></span></div><p>{i.explanation}</p>{i.tags&&<p><b>태그</b> {i.tags}</p>}{i.notes&&<p><b>메모</b> {i.notes}</p>}<div className="actions review-actions"><select value={draft.status} onChange={e=>updateDraft(i.id,{status:e.target.value as CandidateStatus})}>{statusOptions.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select><input placeholder="태그: 예) 여름,저소음,마진확인" value={draft.tags} onChange={e=>updateDraft(i.id,{tags:e.target.value})}/><textarea placeholder="검토 메모" value={draft.notes} onChange={e=>updateDraft(i.id,{notes:e.target.value})} rows={3}/><button className="approve" disabled={busy} onClick={()=>void saveReview(i.id)}>검토 저장</button></div></article>})}
 {tab==="saved"&&sorted.length===0&&<div className="card empty">저장된 상품 후보가 없습니다.</div>}</section></AppShell>
}
